# "/" + ä»“åº“çš„åå­—. èµ„æºæ–‡ä»¶çš„è·¯å¾„ç»„æˆéƒ¨åˆ†
baseurl: "/create-resume-template"
# ä¸»é¢˜é£æ ¼: default | candy
theme-styled: candy

# ç½‘é¡µçš„æ ‡é¢˜
title: æˆ‘çš„ä¸ªäººä¸»é¡µ

# ä¸ªäººæ˜µç§°
username: å¸¸ å‰
# ä¸ªäººç®€ä»‹ï¼Œ æ˜¾ç¤ºåœ¨é¡µé¢çš„æ˜µç§°æ­£ä¸‹æ–¹
typing_text: å…¨æ ˆå·¥ç¨‹å¸ˆï¼Œ ä¸“æ³¨äº Mobile, TDD, DDD ç­‰

# GitHub ä»“åº“çš„ç”¨æˆ·å
github_username: exampleUser
# æ–°æµªå¾®åšçš„ç”¨æˆ·å
weibo_username: exampleUser
# çŸ¥ä¹çš„ç”¨æˆ·å
zhihu_username: exampleUser

# æ˜¯å¦æ˜¾ç¤º å…³äºæˆ‘ è¿™ä¸ªæ¨¡å—ï¼Œ å¦‚æœå€¼ä¸º false, é¡µé¢ä¸ä¼šæ˜¾ç¤ºè¯¥æ¨¡å—
show_aboutme_card: true
# å…³äºæˆ‘æ¨¡å—çš„ æ ‡é¢˜
about_me_title: å…³äºæˆ‘
# å…³äºæˆ‘æ¨¡å—çš„ è¯´æ˜
about_me_description: äººé—´æ¸©æŸ”è§‚å¯Ÿè€…/ğŸ• æŸ çŸ¥åå•¥ä¹Ÿä¸ æ˜¯åšä¸»/å·²è¯»ä¸å›ä¸“ä¸šæˆ·/ğŸ§ é‡åº¦è€³æœºä¾èµ–æ‚£è€…/ğŸ˜’ é€€å½¹é­”æ³•å°‘å¥³

# æ˜¯å¦æ˜¾ç¤º æŠ€èƒ½ è¿™ä¸ªæ¨¡å—ï¼Œ å¦‚æœå€¼ä¸º false, é¡µé¢ä¸ä¼šæ˜¾ç¤ºè¯¥æ¨¡å—
show_skills_card: true
# æŠ€èƒ½æ¨¡å—çš„ æ ‡é¢˜
skills_title: æˆ‘çš„é‚£äº›ä¸ª 666 çš„æŠ€èƒ½ ğŸ˜³

# æŠ€èƒ½æ¨¡å—ä¸­ æŒæ¡çš„è¯­è¨€åå­— name å’ŒæŒæ¡çš„ç¨‹åº¦ weight
# name çš„å€¼è¡¨ç¤ºè¯­è¨€
# weight çš„å€¼è¡¨ç¤ºæŒæ¡ç¨‹åº¦, å¯ä»¥æ˜¯ 5/4/3/2/1 ä¹‹ä¸­çš„ä»»ä½•å€¼. å…¶ä¸­ 5 è¡¨ç¤ºæŒæ¡çš„å¾ˆä¸é”™ï¼Œä¾æ¬¡é€’å‡
skills-languages:
  - name: TypeScript
    weight: 5
  - name: JavaScript
    weight: 4
  - name: Python
    weight: 2
  - name: HTML5
    weight: 4
  - name: CSS3
    weight: 3
  - name: SASS
    weight: 3
  - name: Java
    weight: 1
  - name: Kotlin
    weight: 1
  - name: C++
    weight: 2
  - name: Ruby
    weight: 2

# æŠ€èƒ½æ¨¡å—ä¸­ å–œæ¬¢æˆ–è€…æ“…é•¿çš„çˆ±å¥½. åå­— name å’Œå–œçˆ±çš„ç¨‹åº¦ weight
# name çš„å€¼è¡¨ç¤ºçˆ±å¥½
# weight çš„å€¼è¡¨ç¤ºå–œçˆ±ç¨‹åº¦, å¯ä»¥æ˜¯ 5/4/3/2/1 ä¹‹ä¸­çš„ä»»ä½•å€¼. å…¶ä¸­ 5 è¡¨ç¤ºå¾ˆå–œæ¬¢ï¼Œä¾æ¬¡é€’å‡
life-favorites:
  - name: æ¸¸æ³³
    weight: 5
  - name: æ‘„å½±
    weight: 4
  - name: æ—…è¡Œ
    weight: 2
  - name: ç¾å¦†
    weight: 4

# æŠ€èƒ½æ¨¡å—ä¸­ å…¶å®ƒ. åå­— name å’Œæ„Ÿå…´è¶£çš„ç¨‹åº¦ weight
# name çš„å€¼è¡¨ç¤ºå…¶å®ƒ
# weight çš„å€¼è¡¨ç¤ºæ„Ÿå…´è¶£çš„ç¨‹åº¦, å¯ä»¥æ˜¯ 5/4/3/2/1 ä¹‹ä¸­çš„ä»»ä½•å€¼. å…¶ä¸­ 5 è¡¨ç¤ºå¾ˆæœ‰å…´è¶£ï¼Œä¾æ¬¡é€’å‡
skills-others:
  - name: åˆ›é€ 101
    weight: 2
  - name: åŠ¨æ¼«
    weight: 5
  - name: è¿½æ˜Ÿ
    weight: 4

# æ˜¯å¦æ˜¾ç¤º ä¸ªäººç»å† è¿™ä¸ªæ¨¡å—ï¼Œ å¦‚æœå€¼ä¸º false, é¡µé¢ä¸ä¼šæ˜¾ç¤ºè¯¥æ¨¡å—
show_timeline_card: true
# ä¸ªäººç»å†æ¨¡å—çš„æ ‡é¢˜
timeline_title: å­¦ä¸šå†ç¨‹ & ç»å†

timeline:
  - title: XX å…¬å¸
    title-url: https://example.com/
    date: Mar 2019 - Sep 2020
    subtitle: è½¯ä»¶å·¥ç¨‹å¸ˆ
    tags:
      - tag: Java
      - tag: Typescript
    timeline-side: right

  - title: XX å¤§å­¦
    title-url: https://example.com/
    date: 2017 - 2019
    subtitle: è®¡ç®—æœºç§‘å­¦ä¸æŠ€æœ¯ä¸“ä¸š/å»ºç­‘ä¸“ä¸š/è®¾è®¡ä¸“ä¸š
    timeline-side: left

# å…¶å®ƒé…ç½®ï¼Œå¯å¿½ç•¥
plugins:
  - "jekyll-github-metadata"

exclude:
  [
      "_assets",
      "Gemfile",
      "Gemfile.lock"
  ]



